### ISSUE TITLE
과제에 대한 질문이 있습니다! 🙏

### ISSUE THREAD

**Issue by Hohomii** [Hohomii/Spring_Lv1_Assignment#1]
1. IntelliJ에서 github로 커밋&푸쉬하는 걸 처음 해보았습니다. 인텔리제이에서 하다 보니 코드 수정시 pull 하고 수정하는 방식이 아니라, 따로 pull을 하지 않고 작성하던 인텔리제이 프로젝트에서 바로 수정한 후 커밋&푸쉬하였습니다. 잘 된 것 같긴 한데.. 개인 프로젝트 할 때에는 이런 식으로 해도 되는 걸까요? 

2. 전체 글 조회하는 부분을 짤 때 처음에는 entity의 모든 내역을 작성일시 내림차순으로 가져오게 했었습니다. 그런데 id와 pw값도 같이 넘어와버려서 entity를 반환하지 않고 responseDto를 반환하게 했는데, 작성일시 내림차순 조건도 걸어주어야 해서 검색하여 stream을 썼습니다. 설명을 봐도 잘 이해가 가지 않았는데, 저 부분을 저렇게 해도 되는 건지, stream을 사용하지 않는 다른 방법은 없는지 궁금합니다.

3. responseDto에서 작성일시 보낼 때 제가 한 것처럼 LocalDateTime createdAt 으로 보내주는 게 맞을까요? (postman으로 테스트했을 땐 작성일시가 잘 들어오긴 했습니다..!)

4. 글 조회,작성,수정 시 반환값을 모두 responseDto로 했는데 이렇게 하는 게 맞는지 궁금합니다.^^; (최원빈 튜터님은 어떤 곳에서 getId()를 반환하시기도 하더라고요..)

**Comment by slsnrnsep** [comment]
안녕하세요 호정님! 순회시간 떄에 4가지에 대해 한번 답변은 드렸으나 한번더 짧게 정리하도록 하겠습니다.

1. 개인 프로젝트하실때 브랜치를 나누지 않았더라면 main에 바로 commit & push 하셔도 무방하지만, 앞으로 협업을 생각한다면 브랜치도 나눠보고, 커밋메시지 컨벤션도 나름대로 생각해서 feat : 로그인 기능추가 / fix : 게시글 비밀번호 예외처리 수정 / refactor : 중복함수 제거 등 커밋을 나눠보는 연습을 해보시고 습관을 들이시는게 좋은 방향인 것 같습니다!

2. 내림차순,오름차순 등 sort방법에 대해서는 DB에서 가져올떄부터 sort된채로 가져오기, service단에서 sort시키기의 2가지 방법이 존재할 듯 합니다. 케이스에 따라 자유자재로 사용하는 것이 좋으며 Stream에 대해서는 꼭 Stream을 사용하지 않아도 되지만, 코드 가독성 및 최근 인기있는 언어들에서 함수형 프로그래밍이 선호되고 있으니 사용법을 익히는 것이 좋아보입니다. 그러나, 성능상 꼭 Stream이 유리한가? 에 대한 부분에는 for문이 유리한 경우가 더 많으므로 관련해서 검색해서 개발자가 상황에 맞게 선택적으로 사용하는 것이 좋습니다.

3. entity에는 LocalDateTime 타입으로 저장하고 관리하긴 하지만, 클라이언트단에서 1일전, 3일전 또는 날짜만 왔으면 좋겠다 등의 요구사항이 있을때에는 Dto로 변환할때 String타입으로 가공하여 데이터를 전달하는 것이 좋습니다. 또는 프론트엔드에서 가공해도 관계는 없습니다.

4. Dto에 관련해서는 inner class를 사용해서 응집도를 높이고 각각 다른 경우에 대응할 수 있도록 하는 것을 추천드립니다. 
```
public class PostRequestDto {

    @Getter
    @NoArgsConstructor
    public static class Create {
        private String title;
    }

    @Getter
    @NoArgsConstructor
    public static class Update {
        private String content;
    }

    @Getter
    @NoArgsConstructor
    public static class Delete {
        private String title;
    }
}
```
사용법은 다음과 같으며 사용시에는 PostRequestDto.Create 또는 PostRequestDto.Update처럼 사용하여 코드간의 응집도를 높일 수 있습니다.
@getter와 @NoArgsConstructor 를 붙이는 이유에 대해서는 https://ksh-coding.tistory.com/48 글을 참고하시면 좋을 듯합니다.
